// src/pages/Paste.tsx
import { useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAppStore } from '@/store/useAppStore';
import { api } from '@/lib/api';
import Loading from '@/components/Loading';
import PasswordAuth from '@/components/PasswordAuth';
import PasteView from '@/components/PasteView';
import ManualDeleted from '@/components/ManualDeleted';
import type { PasteResponse } from '@/types';

export default function Paste() {
  const { key } = useParams<{ key: string }>();
  const navigate = useNavigate();
  const { view, config, init, updateState } = useAppStore();

  useEffect(() => {
    const loadPaste = async () => {
      init();
      updateState({ view: 'loading' });

      const url = api.join(config.api.backend, 'paste', key || '');

      try {
        const response: PasteResponse = await api.get(url, {}, [40301, 40402]);

        if (response.code === 40301) {
          updateState({ view: 'password_auth' });
        } else if (response.code === 40402) {
          navigate('/What_are_you_nong_sha_lei');
        } else {
          updateState({
            view: 'paste_view',
            content: response.content || '',
            lang: response.lang === 'plain' ? 'plaintext' : response.lang || ''
          });
        }
      } catch (error) {
        console.error('Failed to load paste:', error);
        navigate('/What_are_you_nong_sha_lei');
      }
    };

    if (key && config.api.backend) {
      loadPaste();
    }
  }, [key, config.api.backend]);

  const renderView = () => {
    switch (view) {
      case 'loading':
        return <Loading />;
      case 'password_auth':
        return <PasswordAuth />;
      case 'paste_view':
        return <PasteView />;
      case 'manual_deleted':
        return <ManualDeleted />;
      default:
        return <Loading />;
    }
  };

  return <div className="py-8">{renderView()}</div>;
}

// src/views/Paste.vue
<template>
    <transition name="component-fade" mode="out-in">
        <component :is="view" v-bind="$data"></component>
    </transition>
</template>

<script>
import stateMixins from "../assets/js/mixins/stateMixin";
import {mapGetters} from "vuex"
import PasswordAuth from "../components/PasswordAuth"
import PasteView from "../components/PasteView";
import Loading from "../components/Loading";
import ManualDeleted from "../components/ManualDeleted";

export default {
    name: "Paste",
    mixins: [stateMixins],
    data() {
        return {}
    },
    computed: {
        ...mapGetters([
            "view",
            "lang",
            "content",
            "config"
        ])
    },
    watch: {
        "$route.params.key": function () {
            this.init();
        }
    },
    mounted() {
        this.init();
    },
    methods: {
        init() {
            this.$store.commit("init");

            this.updateView("loading");
            let url = this.api.join(this.config.api.backend, 'paste', this.$route.params.key)
            this.api.get(url, {}, [40301, 40402]).then(({code, content, lang}) => {
                if (code === 40301) {
                    this.updateView("password_auth");
                } else if (code === 40402) {
                    this.$router.push("What_are_you_nong_sha_lei?");
                } else {
                    this.updateView("paste_view");
                    this.updateContent(content);
                    this.updateLang(lang === "plain" ? "plaintext" : lang);
                }
            });
        },
    },
    components: {
        "password_auth": PasswordAuth,
        "paste_view": PasteView,
        "loading": Loading,
        "manual_deleted": ManualDeleted
    }
}
</script>

<style scoped>
.component-fade-enter-active, .component-fade-leave-active {
    transition: opacity .6s ease;
}

.component-fade-enter, .component-fade-leave-to {
    opacity: 0;
}
</style>
