// src/components/PasswordAuth.vue
<template>
    <b-row>
        <b-col md="4"></b-col>
        <b-col md="4">
            <b-form @submit.prevent="onSubmit">
                <b-form-group :label="$t('lang.auth.form.label')">
                    <b-form-input
                        type="password"
                        v-model="form.password"
                        v-focus
                        :placeholder="flag ? '' : this.$t('lang.auth.form.placeholder')">
                    </b-form-input>
                </b-form-group>
                <b-button type="submit" variant="primary">{{ $t('lang.auth.form.button') }}</b-button>
            </b-form>
        </b-col>
    </b-row>
</template>

<script>
import stateMixin from "../assets/js/mixins/stateMixin";

export default {
    name: "PasswordAuth",
    mixins: [stateMixin],
    data() {
        return {
            flag: true,
            form: {
                password: null,
            }
        }
    },
    methods: {
        onSubmit() {
            const sendUrl = this.api.join(this.$store.getters.config.api.backend, 'paste', this.$route.params.key);
            this.api.get(sendUrl, this.form, false).then(({content, lang}) => {
                this.updateContent(content);
                this.updateLang(lang === "plain" ? "plaintext" : lang);
                this.updateView("paste_view");
            }).catch(error => {
                if (error.response) {
                    let data = error.response.data;
                    if (data.code === 40301) {
                        this.flag = false;
                        this.form.password = null;
                        return
                    } else if (data.code === 40402) {
                        this.$router.push("What_are_you_nong_sha_lei?");
                        return
                    }
                }
                this.api.errorHandler(error);
            });
        }
    }
}
</script>

<style scoped>

</style>

// src/components/PasswordAuth.tsx
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate, useParams } from 'react-router-dom';
import { useAppStore } from '@/store/useAppStore';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { PasteResponse } from '@/types';

export default function PasswordAuth() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { key } = useParams<{ key: string }>();
  const config = useAppStore(state => state.config);
  const updateState = useAppStore(state => state.updateState);
  const [password, setPassword] = useState('');
  const [error, setError] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const url = api.join(config.api.backend, 'paste', key || '');
    try {
      const response: PasteResponse = await api.get(url, { password }, [40301, 40402]);

      if (response.code === 40301) {
        setError(true);
        setPassword('');
      } else if (response.code === 40402) {
        navigate('/What_are_you_nong_sha_lei');
      } else {
        updateState({
          content: response.content || '',
          lang: response.lang === 'plain' ? 'plaintext' : response.lang || '',
          view: 'paste_view'
        });
      }
    } catch (err) {
      setError(true);
      setPassword('');
    }
  };

  return (
    <div className="container mx-auto px-4 max-w-md py-12">
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-sm font-medium mb-2">
            {t('lang.auth.form.label')}
          </label>
          <Input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder={error ? t('lang.auth.form.placeholder') : ''}
            autoFocus
            required
            className={error ? 'border-red-500' : ''}
          />
        </div>
        <Button type="submit">
          {t('lang.auth.form.button')}
        </Button>
      </form>
    </div>
  );
}
