// src/components/PasteView.vue
<template>
    <b-row>
        <b-col md="1"></b-col>
        <b-col md="10">
            <div>
                <b-card no-body>
                    <b-card-header>
                        <b-row>
                            <b-col md="6">
                                <div>
                                    <a>{{ linesCount }} 行</a>
                                    <a>&nbsp;|&nbsp;</a>
                                    <a>{{ $t('lang.view.lang.' + lang) }}</a>
                                </div>
                            </b-col>
                            <b-col md="6" style="text-align: right;">
                                <b-check-group switches>
                                    <b-checkbox v-model="raw" v-if="lang === 'markdown'">源码</b-checkbox>
                                    <b-link id="clipboard-btn" :data-clipboard-text="content">
                                        {{ $t('lang.view.copy') }}
                                    </b-link>
                                    <b-tooltip show target="clipboard-btn" placement="bottomleft">
                                        {{ $t('lang.view.tooltip.' + (copy_btn_status > 0 ? 'success' :
                                        (copy_btn_status === 0 ? 'click' : 'fail'))) }}
                                    </b-tooltip>
                                </b-check-group>
                            </b-col>
                        </b-row>
                    </b-card-header>
                    <div ref="hljs">
                        <b-card-body style="padding-bottom: 0" v-if="lang !== 'markdown' || raw.length === 1">
                            <pre><code v-bind:class="'line-numbers ' + lang" v-text="this.content"></code></pre>
                        </b-card-body>
                        <b-card-body style="padding-bottom: 0" v-else>
                            <div class="markdown-body">
                                <div v-html="markdown.render(content)"></div>
                            </div>
                        </b-card-body>
                    </div>
                </b-card>
            </div>
        </b-col>
        <b-col md="1"></b-col>
    </b-row>
</template>

<script>
    import lineNumbersBlock from '../assets/js/highlightjs-line-numbers'
    import '../assets/css/github-gist.css'
    import '../assets/css/highlightjs-line-numbers.css'
    import { mapGetters } from "vuex"
    export default {
        name: "PasteView",
        data() {
            return {
                copy_btn_status: 0,
                raw: []
            }
        },
        mounted() {
            let clipboard = new this.clipboard('#clipboard-btn');
            let cur = this;
            clipboard.on('success', function () {
                cur.copy_btn_status = 1;
                window.getSelection().removeAllRanges();
                window.setTimeout(function () {
                    cur.copy_btn_status = 0;
                }, 2000);
            });
            clipboard.on('error', function () {
                cur.copy_btn_status = -1;
                window.setTimeout(function () {
                    cur.copy_btn_status = 0;
                }, 2000);
            });
            this.initMermaid();
            this.renderHljs(this.$refs.hljs);
            this.markdownBindHook();
        },
        computed: {
            linesCount: function () {
                let BREAK_LINE_REGEXP = /\r\n|\r|\n/g;
                return (this.content.trim().match(BREAK_LINE_REGEXP) || []).length + 1;
            },
            ...mapGetters([
                "lang",
                "content"
            ])
        },
        methods: {
            renderHljs: function (el) {
                this.$nextTick(() => {
                    let blocks = el.querySelectorAll('pre code');
                    if (document.querySelectorAll('.hljs').length === 0) {
                        blocks.forEach(function (block) {
                            window.hljs.highlightBlock(block);
                            if (block.getAttribute('class').split(' ').indexOf('line-numbers') > -1) {
                                lineNumbersBlock(block, {
                                    singleLine: true
                                });
                            }
                        });
                    }
                })
            },
            initMermaid: function () {
                this.$nextTick(() => {
                    if (this.lang === "markdown") {
                        import("mermaid").then(mermaid => {
                            document.querySelectorAll(".mermaid").forEach(v => {
                                mermaid.init(undefined, v);
                            });
                        })
                    }
                })
            },
            markdownBindHook: function () {
                const _render = this.markdown.render;
                const that = this;
                this.markdown.render = function () {
                    that.initMermaid();
                    return _render.apply(this, arguments);
                }
            }
        },
        watch: {
            raw: function () {
                this.renderHljs(document);
            },
            content: function () {
                this.initMermaid();
            }
        }
    }
</script>
<style>
    .markdown-body code {
        color: black!important
    }
</style>
<style scoped>
    .markdown-body {
        box-sizing: border-box;
        min-width: 200px;
        max-width: 980px;
        margin: 0 auto;
        padding: 45px;
    }

    .markdown-body pre {
        padding-left: 1em;
    }

    @media (max-width: 767px) {
        .markdown-body {
            padding: 15px;
        }
    }
</style>

// src/components/PasteView.tsx
import { useState, useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import ClipboardJS from 'clipboard';
import { useAppStore } from '@/store/useAppStore';
import { markdown } from '@/lib/markdown';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import hljs from 'highlight.js';
import mermaid from 'mermaid';

export default function PasteView() {
  const { t } = useTranslation();
  const { content, lang } = useAppStore();
  const [raw, setRaw] = useState(false);
  const [copyStatus, setCopyStatus] = useState(0);
  const contentRef = useRef<HTMLDivElement>(null);

  const linesCount = content.trim().split(/\r\n|\r|\n/).length;

  useEffect(() => {
    // Initialize clipboard
    const clipboard = new ClipboardJS('#clipboard-btn');

    clipboard.on('success', () => {
      setCopyStatus(1);
      window.getSelection()?.removeAllRanges();
      setTimeout(() => setCopyStatus(0), 2000);
    });

    clipboard.on('error', () => {
      setCopyStatus(-1);
      setTimeout(() => setCopyStatus(0), 2000);
    });

    return () => clipboard.destroy();
  }, []);

  useEffect(() => {
    if (contentRef.current) {
      // Highlight code blocks
      contentRef.current.querySelectorAll('pre code').forEach((block) => {
        hljs.highlightElement(block as HTMLElement);
      });

      // Initialize mermaid diagrams
      if (lang === 'markdown') {
        mermaid.init(undefined, contentRef.current.querySelectorAll('.mermaid'));
      }
    }
  }, [content, lang, raw]);

  const getCopyTooltip = () => {
    if (copyStatus > 0) return t('view.tooltip.success');
    if (copyStatus < 0) return t('view.tooltip.fail');
    return t('view.tooltip.click');
  };

  const renderContent = () => {
    if (lang === 'markdown' && !raw) {
      return (
        <div
          className="markdown-body"
          dangerouslySetInnerHTML={{ __html: markdown.render(content) }}
        />
      );
    }

    return (
      <pre>
        <code className={`language-${lang}`}>{content}</code>
      </pre>
    );
  };

  return (
    <div className="container mx-auto px-4 max-w-6xl">
      <div className="bg-white rounded-lg shadow-lg overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-4 bg-gray-50 border-b">
          <div className="flex items-center gap-4 text-sm text-gray-600">
            <span>{linesCount} {t('view.lines')}</span>
            <span>|</span>
            <span>{t(`view.lang.${lang}`)}</span>
          </div>

          <div className="flex items-center gap-4">
            {lang === 'markdown' && (
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="raw-mode"
                  checked={raw}
                  onCheckedChange={(checked) => setRaw(checked as boolean)}
                />
                <Label htmlFor="raw-mode" className="cursor-pointer text-sm">
                  源码
                </Label>
              </div>
            )}

            <button
              id="clipboard-btn"
              data-clipboard-text={content}
              className="text-blue-600 hover:text-blue-800 text-sm"
              title={getCopyTooltip()}
            >
              {t('view.copy')}
            </button>
          </div>
        </div>

        {/* Content */}
        <div
          ref={contentRef}
          className="p-6 overflow-auto"
          style={{ tabSize: 4 }}
        >
          {renderContent()}
        </div>
      </div>
    </div>
  );
}
