// src/components/Success.tsx
import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { QRCodeSVG } from 'qrcode.react';
import ClipboardJS from 'clipboard';
import { useAppStore } from '@/store/useAppStore';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';

export default function Success() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const key = useAppStore(state => state.key);
  const [copyStatus, setCopyStatus] = useState(0);
  const baseUrl = window.location.origin;
  const pasteUrl = `${baseUrl}/#/${key}`;

  useEffect(() => {
    const clipboard = new ClipboardJS('.copy-badge');

    clipboard.on('success', () => {
      setCopyStatus(1);
      setTimeout(() => setCopyStatus(0), 2000);
    });

    clipboard.on('error', () => {
      setCopyStatus(-1);
      setTimeout(() => setCopyStatus(0), 2000);
    });

    return () => clipboard.destroy();
  }, []);

  const goHome = () => {
    navigate('/');
  };

  const getCopyText = () => {
    if (copyStatus > 0) return t('success.badge.success');
    if (copyStatus < 0) return t('success.badge.fail');
    return t('success.badge.copy');
  };

  return (
    <div className="container mx-auto px-4 max-w-4xl">
      <div className="my-8 bg-white rounded-lg shadow-lg p-8">
        <h2 className="text-3xl font-bold mb-4">{t('success.h2')}</h2>

        <p
          className="mb-4"
          dangerouslySetInnerHTML={{ __html: t('success.p.0.text', { key }) }}
        />

        <ul className="list-disc list-inside space-y-3 mb-6">
          <li>
            <span dangerouslySetInnerHTML={{ __html: t('success.ul.li.0.text') }} />
            &nbsp;
            <Popover>
              <PopoverTrigger asChild>
                <Badge variant="secondary" className="cursor-help">?</Badge>
              </PopoverTrigger>
              <PopoverContent>
                <div dangerouslySetInnerHTML={{ __html: t('success.popover.text') }} />
              </PopoverContent>
            </Popover>
          </li>

          <li>
            {t('success.ul.li.1.browser')}
            &nbsp;
            <a
              href={pasteUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:underline"
              title={t('success.ul.li.1.tooltip')}
            >
              {pasteUrl}
            </a>
            &nbsp;
            <Badge
              variant="default"
              className="copy-badge cursor-pointer"
              data-clipboard-text={pasteUrl}
            >
              {getCopyText()}
            </Badge>
          </li>

          <li>
            <Popover>
              <PopoverTrigger asChild>
                <span className="text-blue-600 cursor-pointer hover:underline">
                  {t('success.ul.li.2.scan_qr_code')}
                </span>
              </PopoverTrigger>
              <PopoverContent>
                <div className="flex justify-center p-2">
                  <QRCodeSVG value={pasteUrl} size={168} />
                </div>
              </PopoverContent>
            </Popover>
          </li>
        </ul>

        <Button onClick={goHome}>
          {t('success.p.1.button')}
        </Button>
      </div>
    </div>
  );
}

// src/components/Success.vue
<template>
    <b-row>
        <b-col md="2"></b-col>
        <b-col md="8" id="success_fixed">
            <div class="jumbotron">
                <h2>
                    {{ $t('lang.success.h2') }}
                </h2>
                <p v-html="$t('lang.success.p[0].text', { key: $parent.key })"></p>
                <ul>
                    <li><a v-html="$t('lang.success.ul.li[0].text')"></a>&nbsp;<b-badge
                            pill class="badge-fixed"
                            href="#"
                            @mouseenter="popover_show = true"
                            @mouseleave="popover_show = false">?</b-badge>
                    </li>
                    <li>{{ $t('lang.success.ul.li[1].browser') }}
                        <a v-b-tooltip.hover="$t('lang.success.ul.li[1].tooltip')"
                           :href="base_url + $parent.key"
                           target="_blank">
                            {{ base_url + $parent.key }}
                        </a>&nbsp;<b-badge
                                variant="info"
                                class="badge-fixed"
                                :data-clipboard-text="base_url + $parent.key"
                                href="#">
                            {{ $t('lang.success.badge.' +
                            (copy_btn_status > 0 ? 'success' : (copy_btn_status === 0 ?  'copy' : 'fail')))  }}
                        </b-badge>
                    </li>
                    <li>
                        <b-link id="qr_code_link">{{ $t('lang.success.ul.li[2].scan_qr_code') }}</b-link>
                    </li>
                </ul>
                <p>
                    <b-button @click.prevent="goHome" variant="primary">{{ $t('lang.success.p[1].button') }}</b-button>
                </p>
            </div>
        </b-col>
        <b-col md="2"></b-col>
        <b-popover
                :show.sync="popover_show"
                target="nav_input"
                placement="bottomright">
            <a v-html="$t('lang.success.popover.text')"></a>
        </b-popover>
        <b-popover
                target="qr_code_link"
                placement="auto"
                triggers="hover">
            <div class="text-center">
                <QRCode :value="this.base_url + this.$parent.key" :options="{ width: 168 }"></QRCode>
            </div>
        </b-popover>
    </b-row>
</template>

<script>
    export default {
        name: "Success",
        data() {
            return {
                base_url: location.origin + '/',
                copy_btn_status: 0,
                popover_show: false,
            }
        },
        mounted() {
            let clipboard = new this.clipboard('.badge-fixed');
            let cur = this;
            clipboard.on('success', function() {
                cur.copy_btn_status = 1;
                window.setTimeout(function () {
                    cur.copy_btn_status = 0;
                }, 2000);
            });
            clipboard.on('error', function() {
                cur.copy_btn_status = -1;
                window.setTimeout(function () {
                    cur.copy_btn_status = 0;
                }, 2000);
            });
        },
        methods: {
            goHome() {
                if (this.$route.params.key !== '') {
                    this.$router.push('/');
                } else {
                    this.$parent.view = 'home';
                }
            }
        }
    }
</script>

<style scoped>
    #success_fixed {
        margin-top: 1.375em;
        margin-bottom: 1.375em;
    }

    .badge-fixed {
        position: relative;
        bottom: .2em;
    }
</style>
